---
title: All papers and preprints
---

```{r paper-flow}
#| warning: false
#| message: false
#| echo: false
#| out.width: "100%"
#| out.height: "2.5in"
#| fig.width: 12
#| fig.height: 2.5
#| column: screen
source(here::here("_rcode/constants.R"))
cols <- paletteer::paletteer_d("MoMAColors::VanGogh")
aRtsy::canvas_slime(background = body_bg, colors = cols, layout = "clusters")
```


```{r, message=FALSE, warning=FALSE, echo=FALSE}
library(bib2df)
library(dplyr)
df <- bib2df(here::here("_biblio", "papers.bib"), separate_names = TRUE)

keep_fields <- toupper(c(
  "category", "author", "booktitle", "edition",
  "editor", "howpublished", "institution", 
  "journal", "pages", "publisher", "number",
  "title", "volume", "year", "arxiv", "url",
  "code", "pdf"))

df <- df[, keep_fields] %>% arrange(desc(YEAR))
source(here::here("_rcode", "render-pubs.R"))

df2 <- df %>%
  transmute(
    year = clean_str(YEAR),
    title = fmt_title(TITLE),
    pub = fmt_jvpy(CATEGORY, JOURNAL, BOOKTITLE, VOLUME, PAGES, year),
    links = fmt_links(URL, ARXIV, PDF, CODE),
    skip = is.na(URL) & is.na(ARXIV) & is.na(PDF) & is.na(CODE)
  )
df2$authors = sapply(df$AUTHOR, fmt_names)
df2 <- df2 %>% filter(!skip)
```

```{r, error=FALSE, warning=FALSE, results="asis", echo=FALSE}
#| column: body
for (i in seq_len(nrow(df2))) {
  ref = df2[i,]
  if (ref$skip) next
  cat(ref$title, "\n")
  cat(ref$authors, "\n")
  cat(ref$pub, "\n")
  cat(ref$links, "\n")
}
```
