---
title: Teaching
---

<!--

## Philosophy

My primary educational goal is to enhance statistical literacy and communication among my students. To me, statistical literacy means combining careful data analysis with scientific expertise to grapple with problems. Given the quantity of data available today, I want my students to learn how to engage in the type of quantitative reasoning and decision making necessary for understanding applications in the sciences, business, and public policy.

Going beyond the didacticism of basic statistical literacy, I strive to inform students about the fundamental role statistics and computation plays in the comprehension of real-world phenomena across disciplines and to motivate them to use this knowledge in their daily lives. Finally, I endeavour to cultivate curiosity in my students and to create an open and nurturing learning environment.

-->

## Current courses

- Stat 302 2025 WT2
- Stat 548 PhD Qualifying [Papers](stat548.qmd)

```{r swirls}
#| warning: FALSE
#| echo: FALSE
#| out-width: "100%"
#| out-height: "2.5in"
#| fig-width: 12 
#| fig-height: 2.5
#| column: screen-left
source(here::here("_rcode/constants.R"))
cols <- paletteer::paletteer_d("MoMAColors::Panton")
aRtsy::canvas_swirls(cols, background = body_bg, n = 100, iterations = 400)
```


## Links to some materials from old courses

#### At UBC

- [Stat 406](https://ubc-stat.github.io/stat-406/) Methods for Statistical Learning
- [Stat 550](https://ubc-stat.github.io/stat-550/) Techniques of Statistical Consulting
- [Stat 535a](https://ubc-stat.github.io/stat-535-convexopt) Topics in Computational Statistics: Convex Optimization

#### At Indiana University, Bloomington

- S100 Statistical Literacy (Sp20)
- S432 Applied Linear Models II (Sp16) (Sp17) (Sp18) (Sp20)
- S771/S772/785 Seminar on Statistical Theory (Fa16--Sp17) (Fa19--Sp20)
- S782 Topics in Statistical Learning Theory (Fa17)

#### At the University of Chicago, Booth School of Business

- 41-911 Advanced Econometrics (Aut18)

#### For CDC/CFA InsightNet and CANSSI Praries

- [Workshop on Aggregate Epidemiological Data and Forecasting](https://cmu-delphi.github.io/insightnet-workshop-2024/)
- [Workshop on Processing and Forecasting with Epidemic Surveillance Data](https://dajmcdon.github.io/canssip-epidata-2025/)

#### At the Institute for New Economic Thinking

- Short Course on Machine Learning ([Sp13](inet2013.qmd)) ([Sp15](inet2015.qmd)) --- As part of the Young Scholars Institute at the INET Hong Kong conference from 2--3 April 2013, Darren Homrighausen and I taught a course on statistical learning. I retaught the course in New York, 24--26 February 2015.
