---
title: "Information for Students"
---


## Research group


### Current members

- Jiaping Liu, PhD in Statistics
- Rachel Lobay, PhD in Statistics
- Xuan Li, PhD in Statstics

### Alumni

- Sarah Masri, MSc in Statistics (UBC 2025)
- Tom Tang, MSc in Statistics (co-supervised with [Jiahua Chen](https://www.stat.ubc.ca/~jhchen/), UBC 2025)
- Christine Chuong, MSc in Statistics (UBC 2025)
- Wakeel Adekunle Kasali, MSc in Statistics (co-supervised with [Nancy Heckman](https://www.stat.ubc.ca/users/nancy-e-heckman), UBC 2025)
- Tigana Runte, MSc in Statistics (UBC 2023); Statistician at Cardiovascular Network of Canada
- Elvis Cai, MSc in Statistics (co-supervised with [Paul Gustafson](http://paulgstf.com/), UBC 2023); Statistician at Centre for Health Evaluation and Outcome Sciences
- William Laplante, MSc in Statistics (co-supervised with [Ben Bloem-Reddy](https://www.stat.ubc.ca/~benbr/), UBC 2023); PhD student at UCL 
- Ken Mawer, NSERC USRA (UBC 2022); MSc student at UWaterloo
- Shuyi Tan, MSc in Statistics (UBC 2022); Data Analyst at VGH & UBC Hospital Foundation
- Xiaoxuan Liang, MSc in Statistics (UBC 2022); PhD student in Computer Science at UBC
- Wei Tang, MSc in Statistics (UBC 2022); Data Scientist at Amazon
- Aaron Cohen, PhD Qualifier (IUB 2021); PhD student in Statistics at IUB
- Lei Ding, PhD in Statistics (IUB 2020); Data Scientist at Amazon
- Robert Granger, PhD Qualifier (IUB 2020); PhD student in Statistics at IUB
- Haoran Liu, MSc in Statistics (IUB 2020); PhD student in Statistics at IUB
- Mackenzie Turner, CEW&T Emerging Scholars REU (IUB 2020); BA student in SPEA at IUB 
- Arash Khodadadi, MSc in Statistics (IUB 2018); Data Scientist at Advanced Microgrid Solutions
- Michael McBride, BSc in Statistics (IUB 2018); Software Developer at Epic
- Jia Wang, MSc in Statistics (IUB 2017); PhD student in Biostatistics at SUNY Buffalo
- Lijiang Guo, PhD Qualifier (IUB 2014); PhD student in ISE at IUB


```{r chladni, warning=FALSE, echo=FALSE, out.width="100%", out.height="2.5in", fig.width=12, fig.height=2.5}
#| column: screen-left
library(ggplot2)
source(here::here("_rcode/constants.R"))
aRtsy::canvas_nebula(colors = paletteer::paletteer_d("MoMAColors::OKeeffe")) +
  theme(panel.background = element_rect(fill = body_bg, color = body_bg)) +
  coord_fixed(ratio = 2.5/12, expand = FALSE)
```


## Applying to UBC Statistics or MDS Programs 

I generally have no special powers when it comes to being admitted to MSc/PhD or
MDS programs. At UBC, students are admitted to the department before choosing an
advisor later in their program. If you are interested, I encourage you to 
consult the [department website](https://www.stat.ubc.ca/graduate).

If you want to learn more, your best bet is to email the 
[Graduate Admissions Officer](mailto:admiss@stat.ubc.ca).

## Requesting letters of recommendation 

I frequently get requests for letters of recommendation, and I'm happy
to comply if I can provide useful information. However, unless we regularly 
interacted, my letter will not help a recruiter or admissions committee member. 
In these cases, I suggest asking someone else who can provide more detailed
descriptions of your unique strengths. 

If you are currently enrolled in class with me, and you would like a letter, I 
will ask that you attend office hours, ask questions, or in another way give me
some information about yourself. Without such interaction, I cannot write a 
helpful letter.

In order for me to write, I will need at least **two** weeks notice before the
first deadline. 

- A description of notable interactions we've had that I should highlight.
This means personal interactions, not a description of the material you liked
in my course.
- If you have a preferred name as well as a given name, please list both.
I need to be able to connect your email to your application and potentially to
your Canvas profile.
- A list of all positions to which you are applying along with deadlines for
each.
- A recent CV or resume that includes a list of courses taken in your major 
and an unofficial transcript.
- A personal statement (likely the one you're sending in one of the
applications).


## Public calendar {#public-calendar}

<div style="display: flex; align-items: center; justify-content: center;">
<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23efefef&amp;ctz=America%2FVancouver&amp;src=ZGFqbWNkb25AZ21haWwuY29t&amp;color=%233F51B5&amp;mode=WEEK&amp;showTitle=0&amp;showPrint=0&amp;showTabs=1&amp;showCalendars=0" style="border-width:0" width="600" height="500" frameborder="0" scrolling="no">
</iframe>
</div>
