---
title: "Postdoctoral research fellowship"
---

### About UBC

The [University of British Columbia](https://www.ubc.ca) is a 
globally-recognized institution for teaching, learning, and research, 
consistently ranked among the top 20 public universities in the world. UBC 
researchers are constantly expanding the boundaries of knowledge and delivering 
innovations to improve lives and address the key challenges of our world. 
Internationally renowned, the [Department of Statistics](https://www.stat.ubc.ca)
is located on the Point Grey campus of The University of British Columbia in 
Vancouver, BC Canada. Faculty members excel in both theory and methodology 
development as well as collaborative research with domain-area experts. The 
Department hosts a vibrant graduate program as well as thriving undergraduate 
programs, with recent initiatives positioning the Department as a hub for 
innovation in statistical education. The Vancouver campus of UBC is situated on
traditional, ancestral, and unceded territory of the xʷməθkʷəy̓əm (Musqueam).

### Job Summary

The Department of Statistics at the University of British Columbia invites
applications for a postdoctoral research fellow under the supervision of 
Prof. Daniel J. McDonald. Opportunities for collaboration across the Department 
of Statistics, the Faculty of Science, and the UBC community will be available.
Collaboration with members of Carnegie Mellon's 
[Delphi Research Group](https://delphi.cmu.edu) as part of its 
[Insight Net Center](https://www.cdc.gov/forecast-outbreak-analytics/partners/insightnet/index.html) will be emphasized. 
While the start date is flexible, the selected candidate will ideally begin no
later than September 2024. 

### Responsibilities
You will work with Prof. McDonald, his research team, and members of Carnegie
Mellon’s Delphi Research Group to develop statistical methods for epidemic 
detection, tracking and forecasting, and their use in decision making, both 
public and private. The postdoctoral fellow is expected to develop statistical
methods and apply them to real-world studies, author and co-author manuscripts 
in peer-reviewed journals, disseminate research findings at professional 
conferences, collaborate with public health professionals, create and manage 
open-source software, and mentor other graduate students. 

### Required Qualifications

* Ph.D. by the time of appointment. Doctoral Candidates in Statistics, Biostatistics, Data 
Science, Computer Science, and/or with experience in infectious disease modeling, 
regardless of the field of graduate studies are encouraged.
* Strong programming skills for statistical computing using R, Python, Julia, or C/C++.


### Desired experience

* Ability to lead: make plans, adapt to new opportunities, drive projects to completion
* Expertise in R package design and development 
* Experience with GitHub and software development in a team setting
* Working knowledge of data science & computational statistics
* Background in Statistical Machine Learning (broadly construed) and / or time series 
* Familiarity with building predictive models in applied settings (like epidemiology) is preferred, but not strictly necessary


### How to Apply:

Applicants should submit (1) a cover letter addressing their specific interest 
in this position, emphasizing directly related skills and experiences, and 
highlighting overall research interests and plan; (2) a curriculum vitae; (3) 
the names and contact information of three references. Please send application 
materials and direct any questions regarding this position to Prof. Daniel J. 
McDonald by email. Applications will be accepted until the position
is filled, but submissions received before 1 April 2024 will receive priority.

### Additional Information

Salary is competitive and commensurate with qualification. In addition to a 
career filled with purpose and opportunity, the University of British Columbia 
offers comprehensive resources and opportunities for all postdoctoral fellows. 
See [here](https://www.postdocs.ubc.ca/resources) for more information.

Vancouver is a large and diverse city with excellent public transportation, 
bike lanes, and an international airport with direct flights throughout North 
America, Europe, and Asia. The city offers close proximity to winter sports, 
mountains, beaches, hiking trails, and other activities as well as rich cultural
experiences. This position is intended to be a two-year appointment. 
Opportunities to build teaching and mentorship experience may be available if 
desired. 

